// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model.proto
// Protobuf C++ Version: 5.29.3

#ifndef model_2eproto_2epb_2eh
#define model_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_model_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_model_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_model_2eproto;
class ModelRequest;
struct ModelRequestDefaultTypeInternal;
extern ModelRequestDefaultTypeInternal _ModelRequest_default_instance_;
class ModelResponse;
struct ModelResponseDefaultTypeInternal;
extern ModelResponseDefaultTypeInternal _ModelResponse_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class ModelResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ModelResponse) */ {
 public:
  inline ModelResponse() : ModelResponse(nullptr) {}
  ~ModelResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ModelResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ModelResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ModelResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline ModelResponse(const ModelResponse& from) : ModelResponse(nullptr, from) {}
  inline ModelResponse(ModelResponse&& from) noexcept
      : ModelResponse(nullptr, std::move(from)) {}
  inline ModelResponse& operator=(const ModelResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ModelResponse& operator=(ModelResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ModelResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ModelResponse* internal_default_instance() {
    return reinterpret_cast<const ModelResponse*>(
        &_ModelResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ModelResponse& a, ModelResponse& b) { a.Swap(&b); }
  inline void Swap(ModelResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ModelResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ModelResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ModelResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ModelResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ModelResponse& from) { ModelResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ModelResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ModelResponse"; }

 protected:
  explicit ModelResponse(::google::protobuf::Arena* arena);
  ModelResponse(::google::protobuf::Arena* arena, const ModelResponse& from);
  ModelResponse(::google::protobuf::Arena* arena, ModelResponse&& from) noexcept
      : ModelResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kModelDataFieldNumber = 1,
  };
  // string modelData = 1;
  void clear_modeldata() ;
  const std::string& modeldata() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_modeldata(Arg_&& arg, Args_... args);
  std::string* mutable_modeldata();
  PROTOBUF_NODISCARD std::string* release_modeldata();
  void set_allocated_modeldata(std::string* value);

  private:
  const std::string& _internal_modeldata() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_modeldata(
      const std::string& value);
  std::string* _internal_mutable_modeldata();

  public:
  // @@protoc_insertion_point(class_scope:ModelResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      31, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ModelResponse& from_msg);
    ::google::protobuf::internal::ArenaStringPtr modeldata_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_model_2eproto;
};
// -------------------------------------------------------------------

class ModelRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ModelRequest) */ {
 public:
  inline ModelRequest() : ModelRequest(nullptr) {}
  ~ModelRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ModelRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ModelRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ModelRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline ModelRequest(const ModelRequest& from) : ModelRequest(nullptr, from) {}
  inline ModelRequest(ModelRequest&& from) noexcept
      : ModelRequest(nullptr, std::move(from)) {}
  inline ModelRequest& operator=(const ModelRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ModelRequest& operator=(ModelRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ModelRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ModelRequest* internal_default_instance() {
    return reinterpret_cast<const ModelRequest*>(
        &_ModelRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ModelRequest& a, ModelRequest& b) { a.Swap(&b); }
  inline void Swap(ModelRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ModelRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ModelRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ModelRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ModelRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ModelRequest& from) { ModelRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ModelRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ModelRequest"; }

 protected:
  explicit ModelRequest(::google::protobuf::Arena* arena);
  ModelRequest(::google::protobuf::Arena* arena, const ModelRequest& from);
  ModelRequest(::google::protobuf::Arena* arena, ModelRequest&& from) noexcept
      : ModelRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kModelNameFieldNumber = 1,
  };
  // string modelName = 1;
  void clear_modelname() ;
  const std::string& modelname() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_modelname(Arg_&& arg, Args_... args);
  std::string* mutable_modelname();
  PROTOBUF_NODISCARD std::string* release_modelname();
  void set_allocated_modelname(std::string* value);

  private:
  const std::string& _internal_modelname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_modelname(
      const std::string& value);
  std::string* _internal_mutable_modelname();

  public:
  // @@protoc_insertion_point(class_scope:ModelRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      30, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ModelRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr modelname_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_model_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ModelRequest

// string modelName = 1;
inline void ModelRequest::clear_modelname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.modelname_.ClearToEmpty();
}
inline const std::string& ModelRequest::modelname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ModelRequest.modelName)
  return _internal_modelname();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ModelRequest::set_modelname(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.modelname_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ModelRequest.modelName)
}
inline std::string* ModelRequest::mutable_modelname() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_modelname();
  // @@protoc_insertion_point(field_mutable:ModelRequest.modelName)
  return _s;
}
inline const std::string& ModelRequest::_internal_modelname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.modelname_.Get();
}
inline void ModelRequest::_internal_set_modelname(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.modelname_.Set(value, GetArena());
}
inline std::string* ModelRequest::_internal_mutable_modelname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.modelname_.Mutable( GetArena());
}
inline std::string* ModelRequest::release_modelname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ModelRequest.modelName)
  return _impl_.modelname_.Release();
}
inline void ModelRequest::set_allocated_modelname(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.modelname_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.modelname_.IsDefault()) {
    _impl_.modelname_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ModelRequest.modelName)
}

// -------------------------------------------------------------------

// ModelResponse

// string modelData = 1;
inline void ModelResponse::clear_modeldata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.modeldata_.ClearToEmpty();
}
inline const std::string& ModelResponse::modeldata() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ModelResponse.modelData)
  return _internal_modeldata();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ModelResponse::set_modeldata(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.modeldata_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ModelResponse.modelData)
}
inline std::string* ModelResponse::mutable_modeldata() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_modeldata();
  // @@protoc_insertion_point(field_mutable:ModelResponse.modelData)
  return _s;
}
inline const std::string& ModelResponse::_internal_modeldata() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.modeldata_.Get();
}
inline void ModelResponse::_internal_set_modeldata(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.modeldata_.Set(value, GetArena());
}
inline std::string* ModelResponse::_internal_mutable_modeldata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.modeldata_.Mutable( GetArena());
}
inline std::string* ModelResponse::release_modeldata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ModelResponse.modelData)
  return _impl_.modeldata_.Release();
}
inline void ModelResponse::set_allocated_modeldata(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.modeldata_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.modeldata_.IsDefault()) {
    _impl_.modeldata_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ModelResponse.modelData)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // model_2eproto_2epb_2eh
