// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: model.proto

#include "model.pb.h"
#include "model.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* ModelLoader_method_names[] = {
  "/ModelLoader/GetModel",
};

std::unique_ptr< ModelLoader::Stub> ModelLoader::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ModelLoader::Stub> stub(new ModelLoader::Stub(channel, options));
  return stub;
}

ModelLoader::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetModel_(ModelLoader_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ModelLoader::Stub::GetModel(::grpc::ClientContext* context, const ::ModelRequest& request, ::ModelResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ModelRequest, ::ModelResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetModel_, context, request, response);
}

void ModelLoader::Stub::async::GetModel(::grpc::ClientContext* context, const ::ModelRequest* request, ::ModelResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ModelRequest, ::ModelResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetModel_, context, request, response, std::move(f));
}

void ModelLoader::Stub::async::GetModel(::grpc::ClientContext* context, const ::ModelRequest* request, ::ModelResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetModel_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ModelResponse>* ModelLoader::Stub::PrepareAsyncGetModelRaw(::grpc::ClientContext* context, const ::ModelRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ModelResponse, ::ModelRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetModel_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ModelResponse>* ModelLoader::Stub::AsyncGetModelRaw(::grpc::ClientContext* context, const ::ModelRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetModelRaw(context, request, cq);
  result->StartCall();
  return result;
}

ModelLoader::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ModelLoader_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ModelLoader::Service, ::ModelRequest, ::ModelResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ModelLoader::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ModelRequest* req,
             ::ModelResponse* resp) {
               return service->GetModel(ctx, req, resp);
             }, this)));
}

ModelLoader::Service::~Service() {
}

::grpc::Status ModelLoader::Service::GetModel(::grpc::ServerContext* context, const ::ModelRequest* request, ::ModelResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


