// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: scene.proto

#include "scene.pb.h"
#include "scene.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* SceneViewer_method_names[] = {
  "/SceneViewer/GetScene",
};

std::unique_ptr< SceneViewer::Stub> SceneViewer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SceneViewer::Stub> stub(new SceneViewer::Stub(channel, options));
  return stub;
}

SceneViewer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetScene_(SceneViewer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SceneViewer::Stub::GetScene(::grpc::ClientContext* context, const ::SceneRequest& request, ::SceneResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::SceneRequest, ::SceneResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetScene_, context, request, response);
}

void SceneViewer::Stub::async::GetScene(::grpc::ClientContext* context, const ::SceneRequest* request, ::SceneResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::SceneRequest, ::SceneResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetScene_, context, request, response, std::move(f));
}

void SceneViewer::Stub::async::GetScene(::grpc::ClientContext* context, const ::SceneRequest* request, ::SceneResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetScene_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::SceneResponse>* SceneViewer::Stub::PrepareAsyncGetSceneRaw(::grpc::ClientContext* context, const ::SceneRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::SceneResponse, ::SceneRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetScene_, context, request);
}

::grpc::ClientAsyncResponseReader< ::SceneResponse>* SceneViewer::Stub::AsyncGetSceneRaw(::grpc::ClientContext* context, const ::SceneRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSceneRaw(context, request, cq);
  result->StartCall();
  return result;
}

SceneViewer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SceneViewer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SceneViewer::Service, ::SceneRequest, ::SceneResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SceneViewer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::SceneRequest* req,
             ::SceneResponse* resp) {
               return service->GetScene(ctx, req, resp);
             }, this)));
}

SceneViewer::Service::~Service() {
}

::grpc::Status SceneViewer::Service::GetScene(::grpc::ServerContext* context, const ::SceneRequest* request, ::SceneResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


