// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: transformtex.proto

#include "transformtex.pb.h"
#include "transformtex.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* TransformTexSync_method_names[] = {
  "/TransformTexSync/GetTransformTex",
};

std::unique_ptr< TransformTexSync::Stub> TransformTexSync::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TransformTexSync::Stub> stub(new TransformTexSync::Stub(channel, options));
  return stub;
}

TransformTexSync::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetTransformTex_(TransformTexSync_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::TransformTexResponse>* TransformTexSync::Stub::GetTransformTexRaw(::grpc::ClientContext* context, const ::TransformTexRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::TransformTexResponse>::Create(channel_.get(), rpcmethod_GetTransformTex_, context, request);
}

void TransformTexSync::Stub::async::GetTransformTex(::grpc::ClientContext* context, const ::TransformTexRequest* request, ::grpc::ClientReadReactor< ::TransformTexResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::TransformTexResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_GetTransformTex_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::TransformTexResponse>* TransformTexSync::Stub::AsyncGetTransformTexRaw(::grpc::ClientContext* context, const ::TransformTexRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::TransformTexResponse>::Create(channel_.get(), cq, rpcmethod_GetTransformTex_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::TransformTexResponse>* TransformTexSync::Stub::PrepareAsyncGetTransformTexRaw(::grpc::ClientContext* context, const ::TransformTexRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::TransformTexResponse>::Create(channel_.get(), cq, rpcmethod_GetTransformTex_, context, request, false, nullptr);
}

TransformTexSync::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TransformTexSync_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< TransformTexSync::Service, ::TransformTexRequest, ::TransformTexResponse>(
          [](TransformTexSync::Service* service,
             ::grpc::ServerContext* ctx,
             const ::TransformTexRequest* req,
             ::grpc::ServerWriter<::TransformTexResponse>* writer) {
               return service->GetTransformTex(ctx, req, writer);
             }, this)));
}

TransformTexSync::Service::~Service() {
}

::grpc::Status TransformTexSync::Service::GetTransformTex(::grpc::ServerContext* context, const ::TransformTexRequest* request, ::grpc::ServerWriter< ::TransformTexResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


