// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: transformtex.proto
#ifndef GRPC_transformtex_2eproto__INCLUDED
#define GRPC_transformtex_2eproto__INCLUDED

#include "transformtex.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

// The service providing transformtex data.
class TransformTexSync final {
 public:
  static constexpr char const* service_full_name() {
    return "TransformTexSync";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::TransformTexResponse>> GetTransformTex(::grpc::ClientContext* context, const ::TransformTexRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::TransformTexResponse>>(GetTransformTexRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::TransformTexResponse>> AsyncGetTransformTex(::grpc::ClientContext* context, const ::TransformTexRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::TransformTexResponse>>(AsyncGetTransformTexRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::TransformTexResponse>> PrepareAsyncGetTransformTex(::grpc::ClientContext* context, const ::TransformTexRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::TransformTexResponse>>(PrepareAsyncGetTransformTexRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetTransformTex(::grpc::ClientContext* context, const ::TransformTexRequest* request, ::grpc::ClientReadReactor< ::TransformTexResponse>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::TransformTexResponse>* GetTransformTexRaw(::grpc::ClientContext* context, const ::TransformTexRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::TransformTexResponse>* AsyncGetTransformTexRaw(::grpc::ClientContext* context, const ::TransformTexRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::TransformTexResponse>* PrepareAsyncGetTransformTexRaw(::grpc::ClientContext* context, const ::TransformTexRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::TransformTexResponse>> GetTransformTex(::grpc::ClientContext* context, const ::TransformTexRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::TransformTexResponse>>(GetTransformTexRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::TransformTexResponse>> AsyncGetTransformTex(::grpc::ClientContext* context, const ::TransformTexRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::TransformTexResponse>>(AsyncGetTransformTexRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::TransformTexResponse>> PrepareAsyncGetTransformTex(::grpc::ClientContext* context, const ::TransformTexRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::TransformTexResponse>>(PrepareAsyncGetTransformTexRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetTransformTex(::grpc::ClientContext* context, const ::TransformTexRequest* request, ::grpc::ClientReadReactor< ::TransformTexResponse>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::TransformTexResponse>* GetTransformTexRaw(::grpc::ClientContext* context, const ::TransformTexRequest& request) override;
    ::grpc::ClientAsyncReader< ::TransformTexResponse>* AsyncGetTransformTexRaw(::grpc::ClientContext* context, const ::TransformTexRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::TransformTexResponse>* PrepareAsyncGetTransformTexRaw(::grpc::ClientContext* context, const ::TransformTexRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetTransformTex_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetTransformTex(::grpc::ServerContext* context, const ::TransformTexRequest* request, ::grpc::ServerWriter< ::TransformTexResponse>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetTransformTex : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetTransformTex() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetTransformTex() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTransformTex(::grpc::ServerContext* /*context*/, const ::TransformTexRequest* /*request*/, ::grpc::ServerWriter< ::TransformTexResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetTransformTex(::grpc::ServerContext* context, ::TransformTexRequest* request, ::grpc::ServerAsyncWriter< ::TransformTexResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetTransformTex<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetTransformTex : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetTransformTex() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::TransformTexRequest, ::TransformTexResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::TransformTexRequest* request) { return this->GetTransformTex(context, request); }));
    }
    ~WithCallbackMethod_GetTransformTex() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTransformTex(::grpc::ServerContext* /*context*/, const ::TransformTexRequest* /*request*/, ::grpc::ServerWriter< ::TransformTexResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::TransformTexResponse>* GetTransformTex(
      ::grpc::CallbackServerContext* /*context*/, const ::TransformTexRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetTransformTex<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetTransformTex : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetTransformTex() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetTransformTex() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTransformTex(::grpc::ServerContext* /*context*/, const ::TransformTexRequest* /*request*/, ::grpc::ServerWriter< ::TransformTexResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetTransformTex : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetTransformTex() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetTransformTex() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTransformTex(::grpc::ServerContext* /*context*/, const ::TransformTexRequest* /*request*/, ::grpc::ServerWriter< ::TransformTexResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetTransformTex(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetTransformTex : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetTransformTex() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->GetTransformTex(context, request); }));
    }
    ~WithRawCallbackMethod_GetTransformTex() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTransformTex(::grpc::ServerContext* /*context*/, const ::TransformTexRequest* /*request*/, ::grpc::ServerWriter< ::TransformTexResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* GetTransformTex(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_GetTransformTex : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_GetTransformTex() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::TransformTexRequest, ::TransformTexResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::TransformTexRequest, ::TransformTexResponse>* streamer) {
                       return this->StreamedGetTransformTex(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_GetTransformTex() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetTransformTex(::grpc::ServerContext* /*context*/, const ::TransformTexRequest* /*request*/, ::grpc::ServerWriter< ::TransformTexResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedGetTransformTex(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::TransformTexRequest,::TransformTexResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_GetTransformTex<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_GetTransformTex<Service > StreamedService;
};


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_transformtex_2eproto__INCLUDED
