// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: transformtex.proto

#include "transformtex.pb.h"
#include "transformtex.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* TransformTexSync_method_names[] = {
  "/TransformTexSync/GetTransformTex",
};

std::unique_ptr< TransformTexSync::Stub> TransformTexSync::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TransformTexSync::Stub> stub(new TransformTexSync::Stub(channel, options));
  return stub;
}

TransformTexSync::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetTransformTex_(TransformTexSync_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TransformTexSync::Stub::GetTransformTex(::grpc::ClientContext* context, const ::TransformTexRequest& request, ::TransformTexResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::TransformTexRequest, ::TransformTexResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetTransformTex_, context, request, response);
}

void TransformTexSync::Stub::async::GetTransformTex(::grpc::ClientContext* context, const ::TransformTexRequest* request, ::TransformTexResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::TransformTexRequest, ::TransformTexResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTransformTex_, context, request, response, std::move(f));
}

void TransformTexSync::Stub::async::GetTransformTex(::grpc::ClientContext* context, const ::TransformTexRequest* request, ::TransformTexResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTransformTex_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TransformTexResponse>* TransformTexSync::Stub::PrepareAsyncGetTransformTexRaw(::grpc::ClientContext* context, const ::TransformTexRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TransformTexResponse, ::TransformTexRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetTransformTex_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TransformTexResponse>* TransformTexSync::Stub::AsyncGetTransformTexRaw(::grpc::ClientContext* context, const ::TransformTexRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetTransformTexRaw(context, request, cq);
  result->StartCall();
  return result;
}

TransformTexSync::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TransformTexSync_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TransformTexSync::Service, ::TransformTexRequest, ::TransformTexResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TransformTexSync::Service* service,
             ::grpc::ServerContext* ctx,
             const ::TransformTexRequest* req,
             ::TransformTexResponse* resp) {
               return service->GetTransformTex(ctx, req, resp);
             }, this)));
}

TransformTexSync::Service::~Service() {
}

::grpc::Status TransformTexSync::Service::GetTransformTex(::grpc::ServerContext* context, const ::TransformTexRequest* request, ::TransformTexResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


